curl --request GET http://localhost:3000/messages/2

# curl -X DELETE http://localhost:3000/messages/1

# curl -X POST -H "Content-Type:application/json" http://localhost:3000/messages -d '{"text":"bruhh"}'

# curl http://localhost:3000/messages/794ab290-8e54-48ef-b77e-e74ce425c3a0